### ISSUE TITLE
Node crashing with "initial block header not found in headers DB"

### ISSUE THREAD

**Issue by pradel** [stacks-network/stacks-blockchain#2992]
**Describe the bug**

I deployed a node on a new server and every time the node is booting I am facing this error after a few hours. 

**Environment (please complete the following information):**

 - Server: fly.io firecracker instance
 - Version: Docker image blockstack/stacks-blockchain:2.05.0.0.0

**Additional context**

```
2022-01-11T08:59:00.429 app[40526511] ams [info]Process abort due to thread panic: panicked at 'FATAL: initial block header not found in headers DB', src/chainstate/stacks/db/blocks.rs:4859:22
2022-01-11T08:59:00.674 app[40526511] ams [info]   0: stacks_node::main::{{closure}}
2022-01-11T08:59:00.674 app[40526511] ams [info]             at src/testnet/stacks-node/src/main.rs:58
2022-01-11T08:59:00.674 app[40526511] ams [info]             at king::rust_panic_with_hook
2022-01-11T08:59:00.674 app[40526511] ams [info]             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:628
2022-01-11T08:59:00.675 app[40526511] ams [info]             at king::begin_panic_handler::{{closure}}
2022-01-11T08:59:00.675 app[40526511] ams [info]             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:521
2022-01-11T08:59:00.675 app[40526511] ams [info]             at ommon::backtrace::__rust_end_short_backtrace
2022-01-11T08:59:00.675 app[40526511] ams [info]             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141
2022-01-11T08:59:00.675 app[40526511] ams [info]             at _unwind
2022-01-11T08:59:00.676 app[40526511] ams [info]             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517
2022-01-11T08:59:00.676 app[40526511] ams [info]   5: core::panicking::panic_fmt
2022-01-11T08:59:00.676 app[40526511] ams [info]             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101
2022-01-11T08:59:00.676 app[40526511] ams [info]   6: core::option::expect_failed
2022-01-11T08:59:00.676 app[40526511] ams [info]             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/option.rs:1615
2022-01-11T08:59:00.677 app[40526511] ams [info]   7: core::option::Option<T>::expect
2022-01-11T08:59:00.677 app[40526511] ams [info]             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/option.rs:698
2022-01-11T08:59:00.678 app[40526511] ams [info]             at _lib::chainstate::stacks::db::blocks::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::get_parent_header_info
2022-01-11T08:59:00.678 app[40526511] ams [info]             at src/src/chainstate/stacks/db/blocks.rs:4853
2022-01-11T08:59:00.679 app[40526511] ams [info]      blockstack_lib::chainstate::stacks::db::blocks::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::process_next_staging_block
2022-01-11T08:59:00.679 app[40526511] ams [info]             at src/src/chainstate/stacks/db/blocks.rs:4991
2022-01-11T08:59:00.680 app[40526511] ams [info]   8: blockstack_lib::chainstate::stacks::db::blocks::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::process_blocks
2022-01-11T08:59:00.680 app[40526511] ams [info]             at src/src/chainstate/stacks/db/blocks.rs:5254
2022-01-11T08:59:00.681 app[40526511] ams [info]   9: blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,N,U,CE,FE>::process_ready_blocks
2022-01-11T08:59:00.681 app[40526511] ams [info]             at src/src/chainstate/coordinator/mod.rs:700
2022-01-11T08:59:00.681 app[40526511] ams [info]  10: blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,N,U,CE,FE>::handle_new_burnchain_block
2022-01-11T08:59:00.681 app[40526511] ams [info]             at src/src/chainstate/coordinator/mod.rs:653
2022-01-11T08:59:00.681 app[40526511] ams [info]  11: blockstack_lib::chainstate::coordinator::ChainsCoordinator<T,blockstack_lib::chainstate::coordinator::comm::ArcCounterCoordinatorNotices,blockstack_lib::chainstate::coordinator::OnChainRewardSetProvider,CE,FE>::run
2022-01-11T08:59:00.681 app[40526511] ams [info]             at src/src/chainstate/coordinator/mod.rs:322
2022-01-11T08:59:00.682 app[40526511] ams [info]             at src/testnet/stacks-node/src/run_loop/neon.rs}}
2022-01-11T08:59:00.682 app[40526511] ams [info]             at src/testnet/stacks-node/src/run_loop/neon.rs:309
2022-01-11T08:59:00.682 app[40526511] ams [info]      std::sys_common::backtrace::__rust_begin_short_backtrace
2022-01-11T08:59:00.682 app[40526511] ams [info]             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:125
2022-01-11T08:59:00.682 app[40526511] ams [info]  13: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
2022-01-11T08:59:00.682 app[40526511] ams [info]             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/mod.rs:481
2022-01-11T08:59:00.682 app[40526511] ams [info]      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
2022-01-11T08:59:00.682 app[40526511] ams [info]             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panic/unwind_safe.rs:271
2022-01-11T08:59:00.682 app[40526511] ams [info]      std::panicking::try::do_call
2022-01-11T08:59:00.682 app[40526511] ams [info]             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403
2022-01-11T08:59:00.682 app[40526511] ams [info]      std::panicking::try
2022-01-11T08:59:00.682 app[40526511] ams [info]             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367
2022-01-11T08:59:00.682 app[40526511] ams [info]      std::panic::catch_unwind
2022-01-11T08:59:00.682 app[40526511] ams [info]             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129
2022-01-11T08:59:00.683 app[40526511] ams [info]      std::thread::Builder::spawn_unchecked::{{closure}}
2022-01-11T08:59:00.683 app[40526511] ams [info]             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/mod.rs:480
2022-01-11T08:59:00.683 app[40526511] ams [info]      core::ops::function::FnOnce::call_once{{vtable.shim}}
2022-01-11T08:59:00.683 app[40526511] ams [info]             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227
2022-01-11T08:59:00.683 app[40526511] ams [info]  14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
2022-01-11T08:59:00.683 app[40526511] ams [info]             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1636
2022-01-11T08:59:00.683 app[40526511] ams [info]      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
2022-01-11T08:59:00.683 app[40526511] ams [info]             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1636
2022-01-11T08:59:00.683 app[40526511] ams [info]      std::sys::unix::thread::Thread::new::thread_start
2022-01-11T08:59:00.683 app[40526511] ams [info]             at rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys/unix/thread.rs:106
```

**Comment by jcnelson** [comment]
Thanks for the stack trace.  I can't say that I've ever seen this error before, even in testing. 

The root cause here is that the following query is returning zero rows, whereas it should always return one row:

```sql
SELECT * FROM block_headers WHERE consensus_hash = "0000000000000000000000000000000000000000" AND block_hash = "0000000000000000000000000000000000000000000000000000000000000000";
```

If this crash happens again, can you try running the above query on `$YOUR_NODE_CHAINSTATE/mainnet/chainstate/vm/index.sqlite3` and tell us what row data it returns (if any)?

**Comment by jcnelson** [comment]
Closing due to inactivity.  Please re-open if the problem persists.
