### ISSUE TITLE
Miner crash due to "Failed to begin new unconfirmed MARF block"

### ISSUE THREAD

**Issue by yknl** [stacks-network/stacks-blockchain#3007]
The miner has been crashing randomly lately. Possibly related to network congestion. It has been running smoothly without any crashes before this week. There were no configuration changes either.

Here's the last few lines from the logs:

```
WARN [1642669759.666833] [testnet/stacks-node/src/burnchains/bitcoin_regtest_controller.rs:1084] [relayer] RBF'd block commits reached 150% satoshi per byte fee rate, not resubmitting
WARN [1642669759.666865] [testnet/stacks-node/src/neon_node.rs:2002] [relayer] Failed to submit Bitcoin transaction
INFO [1642669759.860700] [src/core/mempool.rs:1021] [relayer] TX conflicts with sponsor/origin nonce in same fork with >= fee, new_txid: 70472fab9c340fcd1f63c612230b73f86fbad5abd244532c7ccb5e81c38f047d, old_txid: 1cad58dd918f0891b7ce09ff45108744fbc071ad1922e323cf7cb56d93d43efe, origin_addr: SPBJ2JB5DFF644DFXEVXA1EHJX3RWZP9VB4CZ8NR, origin_nonce: 55, sponsor_addr: SPBJ2JB5DFF644DFXEVXA1EHJX3RWZP9VB4CZ8NR, sponsor_nonce: 55, new_fee: 750000, old_fee: 1200000
WARN [1642669759.860750] [src/net/p2p.rs:4443] [relayer] Transaction rejected from mempool, {"error":"transaction rejected","reason":"ConflictingNonceInMempool","txid":"70472fab9c340fcd1f63c612230b73f86fbad5abd244532c7ccb5e81c38f047d"}
INFO [1642669764.020523] [src/core/mempool.rs:1021] [relayer] TX conflicts with sponsor/origin nonce in same fork with >= fee, new_txid: 817db87fa885a23f6fc2625f920e49f3678e6452e6d98dcf22f21b11d78dbe18, old_txid: 1a91921c6391bf55f0e2cf46dae83def9f8cae795a7aa4160a09bba0d474baf8, origin_addr: SP3YKKE23MAQA1CSQJGWXBKYXMVGGH3G6AYHHBXHR, origin_nonce: 54, sponsor_addr: SP3YKKE23MAQA1CSQJGWXBKYXMVGGH3G6AYHHBXHR, sponsor_nonce: 54, new_fee: 750000, old_fee: 1500000
WARN [1642669764.020590] [src/net/p2p.rs:4443] [relayer] Transaction rejected from mempool, {"error":"transaction rejected","reason":"ConflictingNonceInMempool","txid":"817db87fa885a23f6fc2625f920e49f3678e6452e6d98dcf22f21b11d78dbe18"}
Process abort due to thread panic: panicked at 'ERROR: Failed to begin new unconfirmed MARF block for 02efe25f2a38a3e1103d460928bffdd92514f8e83b480176b0c1fdafd6221fa9): InProgressError', src/clarity_vm/database/marf.rs:199:39
   0: stacks_node::main::{{closure}}
             at /src/testnet/stacks-node/src/main.rs:58
   1: std::panicking::rust_panic_with_hook
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:628
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:521
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:517
   5: core::panicking::panic_fmt
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panicking.rs:101
   6: core::result::unwrap_failed
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1617
   7: core::result::Result<T,E>::expect
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/result.rs:1259
      blockstack_lib::clarity_vm::database::marf::MarfedKV::begin_unconfirmed
             at /src/src/clarity_vm/database/marf.rs:199
   8: blockstack_lib::clarity_vm::clarity::ClarityInstance::begin_unconfirmed
             at /src/src/clarity_vm/clarity.rs:456
   9: blockstack_lib::chainstate::stacks::db::StacksChainState::chainstate_begin_unconfirmed
             at /src/src/chainstate/stacks/db/mod.rs:1863
      blockstack_lib::chainstate::stacks::db::StacksChainState::begin_unconfirmed
             at /src/src/chainstate/stacks/db/mod.rs:1882
  10: blockstack_lib::chainstate::stacks::miner::StacksMicroblockBuilder::resume_unconfirmed
             at /src/src/chainstate/stacks/miner.rs:248
  11: stacks_node::neon_node::mine_one_microblock
             at /src/testnet/stacks-node/src/neon_node.rs:350
      stacks_node::neon_node::try_mine_microblock
             at /src/testnet/stacks-node/src/neon_node.rs:474
      stacks_node::neon_node::run_microblock_tenure
             at /src/testnet/stacks-node/src/neon_node.rs:522
  12: stacks_node::neon_node::spawn_miner_relayer::{{closure}}
             at /src/testnet/stacks-node/src/neon_node.rs:1117
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:125
  13: std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/mod.rs:481
      <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/panic/unwind_safe.rs:271
      std::panicking::try::do_call
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403
      std::panicking::try
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367
      std::panic::catch_unwind
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129
      std::thread::Builder::spawn_unchecked::{{closure}}
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/thread/mod.rs:480
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227
  14: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1636
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/alloc/src/boxed.rs:1636
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys/unix/thread.rs:106
  15: start_thread
  16: __GI___clone

```

**Comment by kantai** [comment]
I believe this is the same issue as https://github.com/stacks-network/stacks-blockchain/issues/2970, so closing this issue in favor of that one.
