### ISSUE TITLE
[Stacks 2.1] Node panics when stacking to pox-2 while already locked to pox-1

### ISSUE THREAD

**Issue by janniks** [stacks-network/stacks-blockchain#3423]
> This bug was encountered during the development of https://github.com/hirosystems/stacks-blockchain-api/pull/1454

**Describe the bug**
A node panics when a user tries to stack to pox-2, while already having stacked to pox-1 (observed in Period-2a).

**Expected behavior**
Even if malicious actions are sent by users, the node should catch these and otherwise fails txs (rather than panic).

---

**Steps To Reproduce**
[Here is an API-test](https://github.com/hirosystems/stacks-blockchain-api/blob/1c6cf08e28c5343f077d0cc6a2c0a29562d373c9/src/tests-2.1-transition/pox-transition-double-stacking.ts#L222-L289) for reproduction or as pseudo-code to follow exactly what's going on.

> In the API-repo the outer-most `describe` is skipped to pass the tests for now...

**Additional Context**

Stack trace / Logs
```
docker-stacks-blockchain-1  | ERRO [1669724165.139653] [testnet/stacks-node/src/main.rs:58] [miner-block-http://0.0.0.0:20443] Process abort due to thread panic: panicked at 'FATAL: failed to lock 2250216000000000 from ST11NJTTKGVT6D1HY4NJRVQWMQM7TVAR091EJ8P2Y until 135: 'PoxAlreadyLocked'', src/clarity_vm/special.rs:684:21
docker-stacks-blockchain-1  | ERRO [1669724165.292751] [testnet/stacks-node/src/main.rs:60] [miner-block-http://0.0.0.0:20443] Panic backtrace:    0: stacks_node::main::{{closure}}
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/testnet/stacks-node/src/main.rs:59:18
docker-stacks-blockchain-1  |    1: std::panicking::rust_panic_with_hook
docker-stacks-blockchain-1  |              at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:702:17
docker-stacks-blockchain-1  |    2: std::panicking::begin_panic_handler::{{closure}}
docker-stacks-blockchain-1  |              at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:588:13
docker-stacks-blockchain-1  |    3: std::sys_common::backtrace::__rust_end_short_backtrace
docker-stacks-blockchain-1  |              at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
docker-stacks-blockchain-1  |    4: rust_begin_unwind
docker-stacks-blockchain-1  |              at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
docker-stacks-blockchain-1  |    5: core::panicking::panic_fmt
docker-stacks-blockchain-1  |              at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
docker-stacks-blockchain-1  |    6: blockstack_lib::clarity_vm::special::handle_stack_lockup
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/src/clarity_vm/special.rs:684:21
docker-stacks-blockchain-1  |       blockstack_lib::clarity_vm::special::handle_pox_v2_api_contract_call
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/src/clarity_vm/special.rs:868:9
docker-stacks-blockchain-1  |    7: blockstack_lib::clarity_vm::special::handle_contract_call_special_cases
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/src/clarity_vm/special.rs:931:16
docker-stacks-blockchain-1  |    8: clarity::vm::contexts::Environment::inner_execute_contract::{{closure}}
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/clarity/./src/vm/contexts.rs:1183:25
docker-stacks-blockchain-1  |       clarity::vm::contexts::Environment::inner_execute_contract
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/clarity/./src/vm/contexts.rs:1149:9
docker-stacks-blockchain-1  |    9: clarity::vm::contexts::Environment::execute_contract
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/clarity/./src/vm/contexts.rs:1111:9
docker-stacks-blockchain-1  |       clarity::vm::contexts::OwnedEnvironment::execute_transaction::{{closure}}
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/clarity/./src/vm/contexts.rs:758:13
docker-stacks-blockchain-1  |       clarity::vm::contexts::OwnedEnvironment::execute_in_env
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/clarity/./src/vm/contexts.rs:667:13
docker-stacks-blockchain-1  |       clarity::vm::contexts::OwnedEnvironment::execute_transaction
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/clarity/./src/vm/contexts.rs:757:9
docker-stacks-blockchain-1  |   10: clarity::vm::clarity::TransactionConnection::run_contract_call::{{closure}}
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/clarity/./src/vm/clarity.rs:291:17
docker-stacks-blockchain-1  |       <blockstack_lib::clarity_vm::clarity::ClarityTransactionConnection as clarity::vm::clarity::TransactionConnection>::with_abort_callback::{{closure}}::{{closure}}
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/src/clarity_vm/clarity.rs:1236:30
docker-stacks-blockchain-1  |       <blockstack_lib::clarity_vm::clarity::ClarityTransactionConnection as clarity::vm::clarity::TransactionConnection>::with_abort_callback::{{closure}}
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/src/clarity_vm/clarity.rs:1218:13
docker-stacks-blockchain-1  |       <blockstack_lib::clarity_vm::clarity::ClarityTransactionConnection as clarity::vm::clarity::TransactionConnection>::with_abort_callback
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/src/clarity_vm/clarity.rs:1217:9
docker-stacks-blockchain-1  |       clarity::vm::clarity::TransactionConnection::run_contract_call
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/clarity/./src/vm/clarity.rs:289:9
docker-stacks-blockchain-1  |   11: blockstack_lib::chainstate::stacks::db::transactions::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::process_transaction_payload
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/src/chainstate/stacks/db/transactions.rs:942:42
docker-stacks-blockchain-1  |   12: blockstack_lib::chainstate::stacks::db::transactions::<impl blockstack_lib::chainstate::stacks::db::StacksChainState>::process_transaction
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/src/chainstate/stacks/db/transactions.rs:1338:30
docker-stacks-blockchain-1  |   13: blockstack_lib::chainstate::stacks::miner::<impl blockstack_lib::chainstate::stacks::StacksBlockBuilder>::try_mine_tx_with_len
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/src/chainstate/stacks/miner.rs:1601:40
docker-stacks-blockchain-1  |   14: blockstack_lib::chainstate::stacks::miner::<impl blockstack_lib::chainstate::stacks::StacksBlockBuilder>::build_anchored_block::{{closure}}
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/src/chainstate/stacks/miner.rs:2474:41
docker-stacks-blockchain-1  |       blockstack_lib::core::mempool::MemPoolDB::iterate_candidates
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/src/core/mempool.rs:1543:19
docker-stacks-blockchain-1  |   15: blockstack_lib::chainstate::stacks::miner::<impl blockstack_lib::chainstate::stacks::StacksBlockBuilder>::build_anchored_block
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/src/chainstate/stacks/miner.rs:2401:39
docker-stacks-blockchain-1  |   16: stacks_node::neon_node::BlockMinerThread::run_tenure
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/testnet/stacks-node/src/neon_node.rs:1792:44
docker-stacks-blockchain-1  |   17: stacks_node::neon_node::RelayerThread::block_miner_thread_try_start::{{closure}}
docker-stacks-blockchain-1  |              at /home/runner/work/stacks-regtest-env/stacks-regtest-env/stacks-blockchain-repo/testnet/stacks-node/src/neon_node.rs:2910:28
docker-stacks-blockchain-1  |       std::sys_common::backtrace::__rust_begin_short_backtrace
docker-stacks-blockchain-1  |              at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:122:18
docker-stacks-blockchain-1  |   18: std::thread::Builder::spawn_unchecked_::{{closure}}::{{closure}}
docker-stacks-blockchain-1  |              at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/mod.rs:514:17
docker-stacks-blockchain-1  |       <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
docker-stacks-blockchain-1  |              at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panic/unwind_safe.rs:271:9
docker-stacks-blockchain-1  |       std::panicking::try::do_call
docker-stacks-blockchain-1  |              at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:492:40
docker-stacks-blockchain-1  |       std::panicking::try
docker-stacks-blockchain-1  |              at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:456:19
docker-stacks-blockchain-1  |       std::panic::catch_unwind
docker-stacks-blockchain-1  |              at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panic.rs:137:14
docker-stacks-blockchain-1  |       std::thread::Builder::spawn_unchecked_::{{closure}}
docker-stacks-blockchain-1  |              at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/thread/mod.rs:513:30
docker-stacks-blockchain-1  |       core::ops::function::FnOnce::call_once{{vtable.shim}}
docker-stacks-blockchain-1  |              at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/ops/function.rs:248:5
docker-stacks-blockchain-1  |   19: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
docker-stacks-blockchain-1  |              at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
docker-stacks-blockchain-1  |       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
docker-stacks-blockchain-1  |              at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
docker-stacks-blockchain-1  |       std::sys::unix::thread::Thread::new::thread_start
docker-stacks-blockchain-1  |              at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys/unix/thread.rs:108:17
docker-stacks-blockchain-1  |   20: start_thread
docker-stacks-blockchain-1  |   21: <unknown>
docker-stacks-blockchain-1  | 
docker-stacks-blockchain-1  | Dumping core for pid 24
```

**Comment by jcnelson** [comment]
This should be fixed in #3409

**Comment by jcnelson** [comment]
Is this fixed?

**Comment by janniks** [comment]
API test to verify: https://github.com/hirosystems/stacks-blockchain-api/pull/1476/commits/5d76760f2757a3b284e684b8cdcb5c2bcb04269c

**Comment by janniks** [comment]
We have noticed the tx result isn't the typical `err 3` from clarity, but a `err none` (from interposing?) — probably intended that way...
https://github.com/hirosystems/stacks-blockchain-api/commit/5d76760f2757a3b284e684b8cdcb5c2bcb04269c
